### PR TITLE
Modified install.rdf

### PR DESCRIPTION
**Pull request by NiveusLuna**
Had to modify the install.rdf file to make the SeaMonkey API versions match the listed Firefox and Thunderbird versions.

I'm sorry about the other files. I can't seem to get them to go away in the pull request.

### CODE REVIEW

**Comment by kylehuff** [comment]
While this pull request will merge successfully into webpg-firefox:master, it will break the application because our branches have diverged by a great extent.

I have made the modification to the install.rdf manually in my repository, and the next release will encompass your change.

I appreciate the involvement and I would like to be able to merge your pull requests in the future; however I won't be able to do so unless you re-align our repositories.

**Comment by NiveusLuna** [comment]
Darn it! Sorry about that.

How do I do that? rm -rf everything, commit, then re-pull? Do I need to use rebase?

Please forgive my ignorance. I'm not _exactly_ new to git, the Fedora Project uses it for their source control, but I've never actually worked with my own individual repo, separate from upstream's, before.

**Comment by kylehuff** [comment]
Personally, I would just drop the repo and re-fork it. I don't experiment with git enough to have a better suggestion.

**Comment by darkpixel** [comment]
git add remote upstream git://github.com/kylehuff/webpg-firefox.git
git fetch upstream

Then something like:
git checkout -b my-new-branch upstream/master

When your new feature branch is ready for pull, 'git push -u origin my-new-branch' and it'll push up to your fork.

**Pull request closed without merging**
